Added k8S deployment file

diff --git a/sbin/ext/dss-framework-project-server b/sbin/ext/dss-framework-project-server
--- a/sbin/ext/dss-framework-project-server
+++ b/sbin/ext/dss-framework-project-server
@@ -1,10 +1,4 @@
 #!/bin/bash
-#
-# description:  ecm start cmd
-# @author:      peacewong
-# @created:     01.16.2021
-#
-# Modified for Linkis 1.0.0
 
 # get log directory
 cd `dirname $0`
@@ -36,9 +30,15 @@ then
   export SERVER_HEAP_SIZE="512M"
 fi
 
+DEBUG_PORT=
+if [ "$DEBUG_PORT" ];
+then
+   export DEBUG_CMD="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=$DEBUG_PORT"
+fi
+
 if test -z "$SERVER_JAVA_OPTS"
 then
-  export SERVER_JAVA_OPTS="-DserviceName=$SERVER_SUFFIX -Xmx$SERVER_HEAP_SIZE -XX:+UseG1GC -Xloggc:$SERVER_LOG_PATH/$SERVER_SUFFIX.log"
+  export SERVER_JAVA_OPTS="-DserviceName=$SERVER_SUFFIX -Xmx$SERVER_HEAP_SIZE -XX:+UseG1GC -Xloggc:$SERVER_LOG_PATH/$SERVER_SUFFIX.gc $DEBUG_CMD"
 fi
 
 export SERVER_CLASS=com.webank.wedatasphere.dss.framework.project.server.DSSProjectServerApplication
@@ -67,17 +67,24 @@ fi
 export SERVER_PID=$DSS_HOME/pid/${SERVER_SUFFIX}.pid
 ## set class path
 export SERVER_CLASS_PATH=$SERVER_CONF_PATH:$DSS_COMMONS_LIB/*:$SERVER_LIB/*
-
-nohup java $SERVER_JAVA_OPTS -cp $SERVER_CLASS_PATH $SERVER_CLASS 2>&1 > $SERVER_LOG_PATH/$SERVER_SUFFIX.out &
-pid=$!
-
-sleep 2
-if [[ -z "${pid}" ]]; then
-    echo "server $SERVER_SUFFIX start failed!"
-    exit 1
-else
-    echo "server $SERVER_SUFFIX start succeeded!"
-    echo $pid > $SERVER_PID
-    sleep 1
+if [ "$EUREKA_PREFER_IP" == "true" ]; then
+  SPRING_ARGS="$SPRING_ARGS --eureka.instance.prefer-ip-address=true "
+  SPRING_ARGS="$SPRING_ARGS --eureka.instance.instance-id=\${spring.cloud.client.ip-address}:\${spring.application.name}:\${server.port}"
 fi
-exit 1
+if [ "X${RUN_IN_FOREGROUND}" == "Xtrue" ]; then
+  java $SERVER_JAVA_OPTS -cp $SERVER_CLASS_PATH $SERVER_CLASS $SPRING_ARGS 2>&1
+else
+  nohup java $SERVER_JAVA_OPTS -cp $SERVER_CLASS_PATH $SERVER_CLASS $SPRING_ARGS 2>&1 > $SERVER_LOG_PATH/$SERVER_SUFFIX.out &
+  pid=$!
+
+  sleep 2
+  if [[ -z "${pid}" ]]; then
+      echo "server $SERVER_SUFFIX start failed!"
+      exit 1
+  else
+      echo "server $SERVER_SUFFIX start succeeded!"
+      echo $pid > $SERVER_PID
+      sleep 1
+  fi
+  exit 1
+fi
